# Page settings
baseurl = "http://padahari.com"
title = "Persembahan Pada Hari Istimewa"
languageCode = "en-us"
theme = "hugo-elate-theme"

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.

[params]
  logo = true
  custom_css = ["css/style2.css", "css/animate.css", "css/magnific-popup.css"]

  # Meta
  author = "Muhammad Aswan Syahputra"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Padahari"
    home = "Beranda"
    work = "Portofolio"
    testimonials = "Testimoni"
    services = "Keunggulan"
    about = "Tentang Kami"
    contact = "Kontak"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    [[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Pada<b>hari</b> ini, Anda istimewa..."
    subtitle = 'Percayakan kebahagiaan Pada<b>hari</b> istimewa Anda kepada kami'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Undangan"
    description = "Anda dapat memesan desain undangan cetak, undangan digital, beserta undangan dalam format video."
    url = "/undangan/"
    button = "Buat undangan"
    icon = "icon-envelope-letter"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Suvenir"
    description = "Anda dapat memesan suvenir cantik untuk pernikahan yang didesain sesuai keinginan dan harapan."
    url = "/suvenir/"
    button = "Buat suvenir"
    icon = "icon-handbag"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Seserahan"
    description = "Anda dapat menyewa perlengkapan seserahan atau mempercayakan kami untuk menghias paket seserahan Anda."
    url = "/seserahan/"
    button = "Buat seserahan"
    icon = "icon-present"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Tonton video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Portofolio"
    description = "Beberapa karya kami untuk kebahagiaan Pada<b>hari</b> istimewa mereka."
    footertext = ''

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu1"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu2"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu3"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu4"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu5"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"

    [[params.work.row]]
      img = "nisa_danu.png"
      alt = "nisa_danu6"
      title = "Siti Anisa Hidayanti & Danu Septian"
      subtitle = "Undangan & Suvenir"
  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Apa kata mereka"
    description = "Kebahagiaan bagi kami karena menjadi bagian Pada<b>hari</b> istimewa mereka."

    [[params.testimonials.item]]
      quote = "&ldquo;Makasih banget bangeeetttt nadiiineeeee, aku suka banget desain undangannya, lucu banget, aku banget dan sesuai dengan requestnya akuuuu, simple but chic 💕 memang ter-BISA diandelin deh pake jasa nadine, oiya e-invitationnya juga lucuukkk, ditambah story yg memang made by request dari aku juga, pokoknya I love it ❤&rdquo;"
      person = 'Siti Anisa Hidayanti<span class="subtext">Cianjur</span>'
      img = "person1.jpeg"
      alt = "Siti Anisa Hidayanti"

    [[params.testimonials.item]]
      quote = "&ldquo;Makasih banget bangeeetttt nadiiineeeee, aku suka banget desain undangannya, lucu banget, aku banget dan sesuai dengan requestnya akuuuu, simple but chic 💕 memang ter-BISA diandelin deh pake jasa nadine, oiya e-invitationnya juga lucuukkk, ditambah story yg memang made by request dari aku juga, pokoknya I love it ❤&rdquo;"
      person = 'Siti Anisa Hidayanti<span class="subtext">Cianjur</span>'
      img = "person1.jpeg"
      alt = "Siti Anisa Hidayanti2"

    [[params.testimonials.item]]
      quote = "&ldquo;Makasih banget bangeeetttt nadiiineeeee, aku suka banget desain undangannya, lucu banget, aku banget dan sesuai dengan requestnya akuuuu, simple but chic 💕 memang ter-BISA diandelin deh pake jasa nadine, oiya e-invitationnya juga lucuukkk, ditambah story yg memang made by request dari aku juga, pokoknya I love it ❤&rdquo;"
      person = 'Siti Anisa Hidayanti<span class="subtext">Cianjur</span>'
      img = "person1.jpeg"
      alt = "Siti Anisa Hidayanti3"

  # Services section
  [params.services]
    enable = true
    title = "Keunggulan"
    description = "Alasan mempercayakan kebahagiaan Pada<b>hari</b> istimewa Anda kepada kami."

    [[params.services.item]]
      title = "Personal"
      description = "Kami percaya bahwa setiap orang adalah istimewa, maka kami menghadirkan kepribadian Anda yang tertuang dalam desain karya. Setiap desain yang kami buat adalah satu-satunya."
      icon = "icon-user-following"

    [[params.services.item]]
      title = "Hemat"
      description = "Kami yakin bahwa kualitas dan kesederhanaan dapat berjalan beriringan. Anda dapat memangkas anggaran dengan menggunakan berbagai pilihan karya dari kami."
      icon = "icon-wallet"

    [[params.services.item]]
      title = "Kekinian"
      description = "Kami menawarkan karya dengan desain masa kini yang ideal untuk diunggah dan dibagikan melalui Instagram, Instagram Story, Facebook, maupun media sosial pilihan Anda lainnya."
      icon = "icon-rocket"

      [[params.services.item]]
      title = "Berwawasan Lingkungan"
      description = "Kami memiliki prinsip untuk menjaga bumi, karenanya setiap karya yang ditawarkan sebisa mungkin dirancang ramah lingkungan: undangan digital dan kemasan seserahan yang tidak sekali pakai."      
      icon = "icon-globe"

      [[params.services.item]]
      title = "Sepenuh Hati"
      description = "Kami bekerja atas dasar kecintaan akan dunia desain dan bisnis kebahagiaan, sehingga setiap karya yang dihasilkan dapat dinikmati dan memberikan kebahagiaan untuk Anda."
      icon = "icon-heart"

      [[params.services.item]]
      title = "Layanan"
      description = "Kami percaya bahwa karya yang terbaik tercipta dari komunikasi yang prima. Kami siap mendengarkan dan melayani hingga mendapatkan karya yang sesuai dengan harapan Anda."      
      icon = "icon-support"

  # About section
  [params.about]
    enable = true
    title = "Tentang Kami"
    description = "Pada<b>hari</b> dibangun dan ditumbuhkan dengan cinta."

    [[params.about.item]]
      name = "Nadine Pricilia"
      position = "CEO, Designer"
      description = ""
      img = "nadine.jpeg"
      alt = "Nadine"
      social = [
        ["icon-globe", "https://nadinepricilia.com"],
	["icon-instagram", "https://instagram.com/nadinepricilia"],
        ["icon-facebook", "https://facebook.com/nadine.pricilia"],
        ["icon-tumblr", "https://nadinepricilia.tumblr.com"],
        ["icon-linkedin", "https://linkedin.com/in/nadine-pricilia-5a927a88"]
      ]

    [[params.about.item]]
      name = "Muhammad Aswan Syahputra"
      position = "CTO"
      description = ""
      img = "aswan.jpg"
      alt = "Aswan"
      social = [
        ["icon-globe", "https://aswansyahputra.com"],
	["icon-github", "https://github.com/aswansyahputra"],
	["icon-linkedin", "https://linkedin.com/in/aswansyahputra"]
      ]
      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Hubungi Kami"
    description = "Ceritakan rencana dan impian, kami bantu mewujudkan kebahagiaan Anda."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Kota Cimahi"],
        ["icon-phone", '<a href="https://api.whatsapp.com/send?phone=+31647609782&text=Halo%20saya%20tertarik%20dengan%20layanan%20PadaHari" target="_blank">Kirim Whatsapp ke Pada<b>hari</b></a>'],
        ["icon-social-instagram", '<a href="https://instagram.com/padahari_" target="_blank">Lihat Instagram Pada<b>hari</b></a>']
      ]

    name = "Nama"
    email = "Surel"
    phone = "Nomor ponsel"
    message = "Pesan"
    button = "Kirim pesan"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-instagram", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
